# Generated by Django 4.1.1 on 2023-04-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0002_achidetails_add_subject_certidetails_document_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_subject',
        ),
    ]
