# Generated by Django 4.1.1 on 2023-05-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interapp', '0005_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='achidetails',
            fields=[
                ('achi_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('achiname', models.CharField(max_length=100, null=True)),
                ('achiinfo', models.CharField(max_length=100, null=True)),
                ('achidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='certidetails',
            fields=[
                ('cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('certiname', models.CharField(max_length=100, null=True)),
                ('cerinfo', models.CharField(max_length=100, null=True)),
                ('certidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='interdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('interns', models.CharField(max_length=100, null=True)),
                ('internname', models.CharField(max_length=100, null=True)),
                ('interndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='projectdetails',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('proname', models.CharField(max_length=100, null=True)),
                ('prodetails', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
